spring.application.name=employee-management

spring.datasource.url=jdbc:postgresql://localhost:5432/employee_management
spring.datasource.username=postgres
spring.datasource.password=Praveena@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

##1gAj7yJr04y4VBfyoKD6YDqcwKK18TQK##
server.port=${PORT:10000}
server.address=0.0.0.0